export const translates = {
    available: 'Доступно',
    leadtime: 'Срок поставки',
    type: 'Тип устройства',
    brand: 'Производитель',
    partnumber: 'Компонент',
    partNumber: 'Компонент',
    frequencyRange: 'Диапазоны частот',
    gain: 'Усиление',
    connectorType: 'Тип разъема',
    measuringRange: 'Диапазон измерений',
    displacementInstability: 'Нестабильность смещения (Аллан)',
    interface: 'Интерфейс',
    supplyVoltage: 'Напряжение питания',
    operatingTemperature: 'Рабочая температура',
    dimensions: 'Габариты',
    weight: 'Масса',
    connector: 'Соединитель',
    housing: 'Корпус',
    technology: 'Технология',
    voltage: 'Напряжение, В',
    frequency: 'Частота',
    polarity: 'Полярность',
    series: 'Серия',
    consumption: 'Потребление',
    operatingModes: 'Режимы работы',
    direction: 'Направление (ось) чувствительности',
    outputInterface: 'Выходной интерфейс',
    series: 'Серия',
    range: 'Диапазон',
    threshold: 'Порог/Разрешение (μg)',
    offset: 'Смещение k0/k1',
    steepness: 'Крутизна выходной характеристики/масштабный коэффициент k1(mA/g)',
    nonlinearityCoefficient: 'Коэффициент нелинейности второго класса k2/k1(μg /g2)',
    shorttermStabilityμG: '(0g, 4 часа) кратковременная стабильность (μg)',
    shorttermStabilityPpm: '(1g, 4 часа) кратковременная стабильность (ppm)',
    repeatabilityμG: '(0g 2часа) Повторяемость (μg)',
    repeatabilityμG_1: '(1g 2часа) Повторяемость (ppm)',
    repeatabilityPpm: 'Повторяемость дрейфа смещения σ k0 (1σ, one month) (μg)',
    repeatabilityPpm_1: 'Повторяемость масштабного коэффициента σ k1/k1(1σ, one month)(ppm)',
    temperatureOffsetCoefficient: 'Температурный коэффициент смещения',
    temperatureOffsetCoefficientAverage:
        'Температурный коэффициент смещения (среднее значение всей температуры) (Ppm/ºC)',
    temperatureSlopeCoefficient: 'Температурный коэффициент крутизны выходной хар-ки (ppm/℃)',
    InstallationError: 'Ошибка установки (μrad)',
    noiseSample: 'Шум (сопротивление образца 840 Ом) (mv)',
    naturalFrequency: 'Собственная частота (Hz)',
    bandwidth: 'Пропускная способность (Hz)',
    vibration: 'Вибрация',
    Shock: 'Шок',
    sinusoidalVibration: 'Синусоидальная вибрация',
    resolution: 'Разрешение',
    operatingTemperatureRange: 'Диапазон рабочих температур (℃)',
    StorageTemperatureRange: 'Диапазон температур хранения (℃)',
    voltage: 'Напряжение, В',
    CurrentConsumption: 'Потребляемый ток (mA)',
    consumption: 'Потребление @ ±15VDC',
    temperatureSensor: 'Датчик температуры',
    dimensionsMm: 'Габариты (мм)',
    weightG: 'Вес, г',
}
